package main

import (
	"fmt"
	"strconv"

	"github.com/julien040/anyquery/rpc"
)

func llmCreator(args rpc.TableCreatorArgs) (rpc.Table, *rpc.DatabaseSchema, error) {
	apiKey := args.UserConfig.GetString("api_key")
	if apiKey == "" {
		return nil, nil, fmt.Errorf("api_key must be set in the plugin configuration")
	}
	baseURL := getBaseURL(args.UserConfig.GetString("base_url"))

	return &llmTable{
			client: newAtlasClient(apiKey, baseURL),
			memo:   newMemoStore(),
		}, &rpc.DatabaseSchema{
			PrimaryKey: -1,
			Columns: []rpc.DatabaseSchemaColumn{
				{
					Name:        "model",
					Type:        rpc.ColumnTypeString,
					IsParameter: true,
					IsRequired:  true,
					Description: "The model to use (e.g. deepseek-ai/DeepSeek-V3-0324). List LLM models with SELECT * FROM atlascloud_models WHERE modality = 'llm'",
				},
				{
					Name:        "prompt",
					Type:        rpc.ColumnTypeString,
					IsParameter: true,
					IsRequired:  true,
					Description: "The user message sent to the model",
				},
				{
					Name:        "system_prompt",
					Type:        rpc.ColumnTypeString,
					IsParameter: true,
					IsRequired:  false,
					Description: "An optional system message",
				},
				{
					Name:        "temperature",
					Type:        rpc.ColumnTypeFloat,
					IsParameter: true,
					IsRequired:  false,
					Description: "The sampling temperature (0.0–2.0). Uses the model default when omitted",
				},
				{
					Name:        "max_tokens",
					Type:        rpc.ColumnTypeInt,
					IsParameter: true,
					IsRequired:  false,
					Description: "The maximum number of tokens to generate. Uses the model default when omitted",
				},
				{
					Name:        "response",
					Type:        rpc.ColumnTypeString,
					Description: "The text generated by the model",
				},
				{
					Name:        "finish_reason",
					Type:        rpc.ColumnTypeString,
					Description: "Why the model stopped (e.g. stop, length)",
				},
				{
					Name:        "prompt_tokens",
					Type:        rpc.ColumnTypeInt,
					Description: "The number of tokens in the prompt",
				},
				{
					Name:        "completion_tokens",
					Type:        rpc.ColumnTypeInt,
					Description: "The number of tokens in the response",
				},
			},
		}, nil
}

type llmTable struct {
	client *atlasClient
	memo   *memoStore
}

type llmCursor struct {
	client *atlasClient
	memo   *memoStore
}

func (t *llmTable) CreateReader() rpc.ReaderInterface {
	return &llmCursor{
		client: t.client,
		memo:   t.memo,
	}
}

func (t *llmCursor) Query(constraints rpc.QueryConstraint) ([][]interface{}, bool, error) {
	model := constraints.GetColumnConstraint(0).GetStringValue()
	if model == "" {
		return nil, true, fmt.Errorf("model must be set (e.g. WHERE model = 'deepseek-ai/DeepSeek-V3-0324')")
	}
	prompt := constraints.GetColumnConstraint(1).GetStringValue()
	if prompt == "" {
		return nil, true, fmt.Errorf("prompt must be set (e.g. WHERE prompt = 'Explain SQL in one sentence')")
	}
	systemPrompt := constraints.GetColumnConstraint(2).GetStringValue()

	// Distinguish "not set" from a 0 value for the optional parameters
	var temperature *float64
	temperatureKey := ""
	if cst := constraints.GetColumnConstraint(3); cst != nil && cst.Value != nil {
		value := cst.GetFloatValue()
		temperature = &value
		temperatureKey = strconv.FormatFloat(value, 'f', -1, 64)
	}
	var maxTokens *int64
	maxTokensKey := ""
	if cst := constraints.GetColumnConstraint(4); cst != nil && cst.Value != nil {
		value := cst.GetIntValue()
		if value > 0 {
			maxTokens = &value
			maxTokensKey = strconv.FormatInt(value, 10)
		}
	}

	// Re-scans of the same input tuple within a statement must not trigger
	// a second paid API call
	key := memoKey("llm", model, prompt, systemPrompt, temperatureKey, maxTokensKey)
	if row, hit := t.memo.get(key); hit {
		return [][]interface{}{row}, true, nil
	}

	messages := []chatMessage{}
	if systemPrompt != "" {
		messages = append(messages, chatMessage{Role: "system", Content: systemPrompt})
	}
	messages = append(messages, chatMessage{Role: "user", Content: prompt})

	response, err := t.client.chatCompletion(chatRequest{
		Model:       model,
		Messages:    messages,
		Temperature: temperature,
		MaxTokens:   maxTokens,
		Stream:      false,
	})
	if err != nil {
		return nil, true, err
	}
	if len(response.Choices) == 0 {
		return nil, true, fmt.Errorf("the model returned no response")
	}

	var promptTokens, completionTokens interface{}
	if response.Usage != nil {
		promptTokens = response.Usage.PromptTokens
		completionTokens = response.Usage.CompletionTokens
	}

	// Reasoning models may leave content empty and put the answer in
	// reasoning_content
	content := response.Choices[0].Message.Content
	if content == "" {
		content = response.Choices[0].Message.ReasoningContent
	}

	row := []interface{}{
		content,
		stringOrNil(response.Choices[0].FinishReason),
		promptTokens,
		completionTokens,
	}
	t.memo.set(key, row)

	return [][]interface{}{row}, true, nil
}

func (t *llmTable) Close() error {
	return nil
}
