// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package queries

import (
	"context"
)

const getConnection = `-- name: GetConnection :one
Select uid, connection_id, status, error, updated_at, created_at, metadata from connections where uid = $1
`

func (q *Queries) GetConnection(ctx context.Context, uid string) (Connection, error) {
	row := q.db.QueryRow(ctx, getConnection, uid)
	var i Connection
	err := row.Scan(
		&i.Uid,
		&i.ConnectionID,
		&i.Status,
		&i.Error,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}
