// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package model

import (
	"database/sql"
)

type Alias struct {
	Tablename sql.NullString
	Alias     sql.NullString
}

type PluginInstalled struct {
	ID                sql.NullString
	Name              sql.NullString
	Description       sql.NullString
	Path              string
	Executablepath    string
	Version           string
	Homepage          sql.NullString
	Registry          sql.NullString
	Config            string
	Checksumdir       sql.NullString
	Dev               int64
	Author            sql.NullString
	Tablename         string
	Issharedextension int64
}

type Profile struct {
	Name     sql.NullString
	Pluginid sql.NullString
	Config   string
}

type Registry struct {
	Name             string
	Url              string
	Lastupdated      int64
	Checksumregistry string
	Registryjson     string
}
